### ISSUE TITLE
Add the geoarrow-R to implementations list on website

### ISSUE THREAD

**Issue by ran-codes** [geoarrow/geoarrow.github.io#4]
Can you add https://github.com/geoarrow/geoarrow-r into the GeoArrow implementations list  (snipped below)?

![image](https://github.com/user-attachments/assets/76b41caa-56e2-4705-bcae-2d578d887529)

**Comment by kylebarron** [comment]
I think you can add an element to the list here:
https://github.com/geoarrow/geoarrow.github.io/blob/ce39ecbf3cf25450c0d53ac20610bf8b0b6f2c80/_quarto.yml#L19-L28

**Comment by ran-codes** [comment]
thanks for the quick response; see this pull request https://github.com/geoarrow/geoarrow.github.io/pull/5

**Comment by ran-codes** [comment]
I also submitted a PR to update the geoarrow README.md here - https://github.com/geoarrow/geoarrow/pull/77.

Not sure if you need to refresh the build to pull that change in or not.

Thanks so much for your work on this!

**Comment by kylebarron** [comment]
Closed by https://github.com/geoarrow/geoarrow.github.io/pull/5
